# Generated by Django 6.0 on 2026-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_assigned_staff_alter_complaint_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='hostel_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='room_number',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
