# Generated by Django 6.0 on 2026-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
